# Generated by Django 3.2.3 on 2021-05-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=100)),
                ('para', models.CharField(max_length=1000)),
                ('link_page', models.CharField(max_length=300)),
            ],
        ),
    ]
