# Generated by Django 3.2.3 on 2021-05-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210523_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_banner',
            old_name='images_of_banner',
            new_name='images_of_item',
        ),
    ]
