# Generated by Django 3.2.3 on 2021-05-24 11:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_images_of_banner_top_banner_images_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_banner',
            name='para',
            field=tinymce.models.HTMLField(),
        ),
    ]
