# Generated by Django 3.2.3 on 2021-05-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated']},
        ),
    ]
