# Generated by Django 3.2.3 on 2021-05-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='Deep Store', max_length=100),
        ),
    ]
