# Generated by Django 3.2.3 on 2021-05-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['product_id']},
        ),
    ]
