# Generated by Django 3.2.3 on 2021-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_deal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='deal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
