# Generated by Django 3.2.3 on 2021-05-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210527_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='off_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
